### PR TITLE
DWC App & Controls Annotations

### PR DESCRIPTION
**Pull request by hyyan**
The PR implements the first set of basic annotations to allow configuring the app & **custom control/widget** meta data. The final goal is to have an annotation for most of the [BBjWebManager](https://documentation.basis.cloud/BASISHelp/WebHelp/bui/BBjBuiManager/bbjbuimanager.htm) methods.

### Example:

```java 
import org.dwcj.App;
import org.dwcj.annotations.AppMeta;
import org.dwcj.annotations.AppTheme;
import org.dwcj.annotations.AppTitle;
import org.dwcj.annotations.Attribute;
import org.dwcj.exceptions.DwcException;

@AppTheme("dark")
@AppTitle("Playground custom title")
@AppMeta(name = "author", content = "Hyyan Abo Fakher")
@AppMeta(name = "description", content = "This is a test app")
@AppMeta(name = "keywords", content = "test, app, dwc, bbj")
@AppMeta(name = "custom name", content = "custom content", attributes = {
    @Attribute(name = "custom-attribute", value = "custom attribute value"),
    @Attribute(name = "custom-attribute2", value = "custom attribute value2")
})
public class Playground extends App {

  @Override
  public void run() throws DwcException {
    msgbox("this is a test");
  }
}

```

### Currently implemented: 

1. **AppTitle**: Set the application title on the fly.  (Not the most useful one)
2. **AppTheme**: Set the application them on the fly.
3. **AppMeta**: Set one or more meta tags on the fly.

### Notes

1. The PR does not expose the  [BBjWebManager](https://documentation.basis.cloud/BASISHelp/WebHelp/bui/BBjBuiManager/bbjbuimanager.htm) instance directly and processes the annotations internally before the app is run. Should we expose it or proxy it.(I think we should proxy all methods we want to expose)
2. The PR re-defines `App::run` method to throw a `DwcException` instead of `DwcAppInitializeException`. `DwcAppInitializeException` extends `DwcException`. Added too `DwcAnnotationException`

### CODE REVIEW

**Review by StephanWald — APPROVED** [review]
Nice idea. I would still vote for exposing especially the Theme-selection also somewhere as methods on the App - level, so the application can later change e.g. between dark and light theme, or the user can upload, select a theme file at runtime. Probably not important right now, but still desirable I think. Go ahead and merge this here, though. Nicely done!

**Comment by hyyan** [comment]
* Rebased on pre-0.009 
* Refactored and added new methods in `App.java` to configure meta data.
* Added `AppDarkTheme` annotation
* Added `AppLightTheme` annotation

## Sample

```java
import org.dwcj.App;
import org.dwcj.annotations.AppDarkTheme;
import org.dwcj.annotations.AppTheme;
import org.dwcj.annotations.AppTitle;
import org.dwcj.exceptions.DwcException;

@AppTitle("My app title")
@AppTheme("system")
@AppDarkTheme("dark-pure")
public class Playground extends App {

  @Override
  public void run() throws DwcException {
    msgbox(getTitle());
  }
}

```

**Comment by hyyan** [comment]
* Added attributes annotation and methods

```java
import org.dwcj.App;
import org.dwcj.annotations.AppAttribute;
import org.dwcj.annotations.AppAttributes;
import org.dwcj.annotations.AppTitle;
import org.dwcj.exceptions.DwcException;

@AppTitle("Playground custom title")
@AppAttributes({
    @AppAttribute(name = "custom-attribute", value = "custom attribute value"),
    @AppAttribute(name = "custom-attribute2", value = "custom attribute value2", selector = "body")
})
public class Playground extends App {

  @Override
  public void run() throws DwcException {
    msgbox(getTitle());
  }
}

```

**Comment by hyyan** [comment]
* Added @JavaScript annotation
* Added @InlineJavaScript annotation
* Added @StyleSheet annotation
* Added @InlineStyleSheet annotation

These set of annotations can be used on the app or controls level. All implemented annotations have their own methods in `App.java`

The following is a simple QR Control based on [shoelace](https://shoelace.style/components/qr-code) which utilizes some of these features and how to use them on app and control level.

Recording 2023-01-04 at 03 01 49

```css
/* resources/css/style.css */
.app-panel .BBjWindow > .BBjPanel {
  overflow-y: auto;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-direction: column;
  gap: 1rem;
  height: 100%;
}
```

```java

import org.dwcj.App;
import org.dwcj.annotations.AppTheme;
import org.dwcj.annotations.AppTitle;
import org.dwcj.annotations.InlineStyleSheet;
import org.dwcj.controls.panels.AppPanel;
import org.dwcj.controls.textbox.TextBox;
import org.dwcj.exceptions.DwcException;

@AppTheme("dark")
@AppTitle("QR Code Generator")
@InlineStyleSheet(value = "css/style.css", local = true, id = "app-bundle")
public class Playground extends App {

  @Override
  public void run() throws DwcException {
    AppPanel panel = new AppPanel();
    panel.addClassName("app-panel");

    String defaultValue = "https://dwcj.org/";

    QRCode qr = new QRCode(defaultValue);
    panel.add(qr);
    qr.setSize(200);
    qr.setColor(Color.ORANGE);

    TextBox editBox = new TextBox();
    editBox.setText(defaultValue);
    editBox.setExpanse(TextBox.Expanse.LARGE);
    editBox.setAttribute("placeholder", "Enter a value");
    editBox.onEditModify((e) -> {
      qr.setValue(editBox.getText());
    });

    panel.add(editBox);
  }
}
```

```java
package org.demo;

import java.awt.Color;
import java.util.UUID;

import org.dwcj.annotations.Attribute;
import org.dwcj.annotations.JavaScript;
import org.dwcj.controls.AbstractControl;
import org.dwcj.controls.htmlcontainer.HtmlContainer;
import org.dwcj.controls.panels.AbstractDwcjPanel;

/**
 * QRCode Generator using Shoelace QRCode component
 * 
 * @author Hyyan Abo Fakher
 */
@JavaScript(id = "shoelace-qr-code", url = "https://cdn.jsdelivr.net/npm/@shoelace-style/shoelace@2.0.0-beta.87/dist/shoelace.js", attributes = {
    @Attribute(name = "type", value = "module")
})
final public class QRCode extends AbstractControl {
  private HtmlContainer hv;
  private final String uuid = UUID.randomUUID().toString().substring(0, 8);
  private String value;
  private int size = 65;
  private Color color = Color.BLACK;

  public QRCode() {
    super();
  }

  public QRCode(String value) {
    super();
    this.value = value;
  }

  /**
   * Get the UUID of the toast.
   * 
   * @return the UUID of the toast.
   */
  public String getUUID() {
    return uuid;
  }

  /**
   * Get the value of the QRCode
   * 
   * @return the value of the QRCode
   */
  public String getValue() {
    return value;
  }

  /**
   * Set the value of the QRCode
   * 
   * @param value the value of the QRCode
   */
  public QRCode setValue(String value) {
    this.value = value;
    hv.executeAsyncScript("document.querySelector(\"[data-hv='" + getUUID()
        + "']\").querySelector('sl-qr-code').setAttribute('value', '" + value + "')");
    return this;
  }

  /**
   * Get the size of the QRCode
   * 
   * @return the size of the QRCode
   */
  public int getSize() {
    return size;
  }

  /**
   * Set the size of the QRCode
   * 
   * @param size the size of the QRCode
   */
  public QRCode setSize(int size) {
    this.size = size;
    hv.executeAsyncScript("document.querySelector(\"[data-hv='" + getUUID()
        + "']\").querySelector('sl-qr-code').setAttribute('size', '" + size + "')");
    return this;
  }

  /**
   * Get the color of the QRCode
   * 
   * @return the color of the QRCode
   */
  public Color getColor() {
    return color;
  }

  /**
   * Set the color of the QRCode
   * 
   * @param color the color of the QRCode
   */
  public QRCode setColor(Color color) {
    this.color = color;
    hv.executeAsyncScript("document.querySelector(\"[data-hv='" + getUUID()
        + "']\").querySelector('sl-qr-code').setAttribute('fill', '" + toHexString(color) + "')");
    return this;
  }

  /**
   * Create the control
   * 
   * @param p the parent panel
   */
  protected void create(AbstractDwcjPanel p) {
    super.create(p);

    hv = new HtmlContainer("<sl-qr-code value='" + value + "' size='" + size
        + "' fill='" + toHexString(color) + "'></sl-qr-code>");
    hv.setAttribute("data-hv", getUUID());
    hv.setTabTraversable(false);
    hv.setFocusable(false);

    // add the control to the parent panel
    p.add(hv);
  }

  /**
   * Convert a color to a hex string
   * 
   * @param color the color to convert
   * @return
   */
  private String toHexString(Color color) {
    return String.format("#%02x%02x%02x", color.getRed(), color.getGreen(), color.getBlue());
  }
}
```

**Comment by hyyan** [comment]
* Add @Link annotation

```java
package org.demo;

import org.dwcj.App;
import org.dwcj.annotations.InlineStyleSheet;
import org.dwcj.annotations.Link;
import org.dwcj.annotations.StyleSheet;
import org.dwcj.annotations.Attribute;
import org.dwcj.exceptions.DwcException;

@Link(url = Playground.AppFont, id = "pacifico-font", attributes = {
    @Attribute(name = "rel", value = "preload"),
    @Attribute(name = "as", value = "style"),
})
@StyleSheet(url = Playground.AppFont, id = "pacifico-font")
@InlineStyleSheet(value = ":root{ --bbj-font-family: 'Pacifico'}")
public class Playground extends App {

  static final String AppFont = "https://fonts.googleapis.com/css2?family=Pacifico&display=swap";

  @Override
  public void run() throws DwcException {
    msgbox("Hello World");
  }
}

```

**Comment by hyyan** [comment]
@StephanWald The PR is complete: please review it when your time allows so I can merge.

## Summery

Annotations are processed using the `AnnotationProcessor.java`. When any of the control annotations
is used then they will be processed only when the control is attached to a panel.

All annotations use the public API defined in `App.java`

The PR re-defines `App::run` method to throw a `DwcException` instead of `DwcAppInitializeException`. `DwcAppInitializeException` extends `DwcException`.

### Supported Annotations
1. **AppTitle**: (App Only) Set the application title. This annotation is not working perfectly yet because `AppPanel` keeps overriding the title when it is focused (To be discussed later with Jim)
2. **AppTheme**: (App Only) Set the application theme.
3. **AppMeta**: (App Only) Set one or more meta tags
4. **AppDarkTheme**: (App Only) Set the name of the dark theme to be used by the application when the current theme is `system`
5. **AppLightTheme**: (App Only) Set the name of the light theme to be used by the application when the current theme is `system`
6. **AppAttribute**: (App Only) Set one or more attributes to the application (html tag or different target specified by a selector)
7. **StyleSheet**: (App & Controls) Set one or more stylesheets to be loaded by the application. The annotation is used for external stylesheets. Duplications can be avoided by providing an ID 
8. **InlineStyleSheet**: (App & Controls) Inline one or more stylesheets in the application. The annotation accepts too a local path to a file or a string with the content of the stylesheet. Bundling can be achieved by providing an ID
9. **JavaScript**:  (App & Controls) Set one or more JavaScript to be loaded by the application. The annotation is used for external JavaScript.  Duplications can be avoided by providing an ID
10. **InlineJavaScript**: (App & Controls) Inline one or more JavaScript in the application. The annotation accepts too a local path to a file or a string with the content of the JavaScript.
11. **Link**: (App & Controls) Set one or more links to be injected in the application (for instance fonts)

Samples are provided previously

**Comment by hyyan** [comment]
Duplications reported by [sonarcloud](https://github.com/apps/sonarcloud) cannot be reduced. sonarcloud is not able to figure out that these are two Seperated annotations

**Review by StephanWald — APPROVED** [review]

**Comment by StephanWald** [comment]
Leaving PR in place so we can grab the documentation from it. Assigned to @mhawkinsbasis  for that purpose.

@hyyan how would one load a custom theme file that is created with the DWC Themer? @mhawkinsbasis may also want to add some sample code and maybe later do a video on how to use https://hot.bbx.kitchen/webapp/DWCThemer with DWCJ.

**Comment by hyyan** [comment]
> @hyyan how would one load a custom theme file that is created with the DWC Themer? @mhawkinsbasis may also want to add some sample code and maybe later do a video on how to use https://hot.bbx.kitchen/webapp/DWCThemer with DWCJ.

The file can be loaded from the jar resource (location can be [configured with maven](https://maven.apache.org/plugins/maven-resources-plugin/examples/resource-directory.html)) folder using the InlineStyleSheet annnotation.

```java
@InlineStyleSheet(value = "css/them.css", local = true)
```

Or if the theme is hosted somewhere in a web server then the `@StyleSheet(url=".../theme.css")` can be used.

**Comment by StephanWald** [comment]
We will probably also want to create a sample that allows the user to pick a theme file from his disk, so it's not coming with the code.

**Pull request merged**
