### PR TITLE
feat: Add support for webcomponents integration

### PR DESCRIPTION
**Pull request by hyyan**
1. The PR add a mini-framework to support integrating any arbitrary web component in dwcj.
2. Implement AppLayout component
3. Implement Drawer component
4. Add support for BBj ObjectTable

Note: The PR adds `com.google.code.gson` as a dependency

### CODE REVIEW

**Comment by hyyan** [comment]
Tagging @mhawkinsbasis for documentation

**Review by StephanWald — APPROVED** [review]
looks good to me.

**Comment by hyyan** [comment]
Added dialog component.

login-dialog


```java
import java.util.HashMap;
import java.util.Map;

import org.dwcj.App;
import org.dwcj.annotations.AppTitle;
import org.dwcj.annotations.InlineStyleSheet;
import org.dwcj.controls.button.Button;
import org.dwcj.controls.checkbox.CheckBox;
import org.dwcj.controls.dialog.Dialog;
import org.dwcj.controls.label.Label;
import org.dwcj.controls.panels.AppPanel;
import org.dwcj.controls.textbox.TextBox;
import org.dwcj.exceptions.DwcException;
import org.dwcj.webcomponent.events.Event;
import org.dwcj.webcomponent.events.EventDispatcher;
import org.dwcj.webcomponent.events.EventListener;

@AppTitle("Customer Portal | DWCJ")
public class Login extends App {

  /**
   * {@inheritDoc}
   */
  @Override
  public void run() throws DwcException {
    AppPanel panel = new AppPanel();

    FormDialog form = new FormDialog();
    form.addLoginListener((LoginEvent e) -> {
      String username = e.getUserName();
      String password = e.getPassword();

      if (username.equals("admin") && password.equals("admin")) {
        // login success
        form.hide();
        msgbox("Welcome " + username, 0, "Login success");
      } else {
        // login failed
        form.showError("Invalid username or password. Use 'admin' for both fields.");
      }
    });

    panel.add(form);
    form.show();
  }

  /**
   * A server-side component that represent a login form based on the dwcj dialog
   * component.
   */
  @InlineStyleSheet(id = "login-form", value = "" +
      ".loginForm {" +
      "   background-color: #263238;" +
      "   background-image: url(https://customer.iitsd.cloud/assets/images/login-pattern.png);" +
      "   background-size: 100% 100%;" +
      "   background-repeat: no-repeat;" +
      "}" +
      ".loginForm [slot='header'] {" +
      "  text-align: center;" +
      "  border-bottom: thin solid var(--bbj-color-default) !important" +
      "}" +
      ".loginForm [slot='content'] {" +
      "  display: flex;" +
      "  flex-direction: column;" +
      "  gap: 1em;" +
      "}" +
      ".loginForm [slot='footer'] {" +
      "   background: var(--bbj-surface-1);" +
      "}" +
      ".loginForm__error {" +
      "   border: thin solid var(--bbj-color-danger);" +
      "   background: var(--bbj-color-danger-alt);" +
      "   color: var(--bbj-color-on-danger-text-alt);" +
      "   padding: var(--bbj-space-s);" +
      "   border-radius: var(--bbj-border-radius-s);" +
      "}")
  private class FormDialog extends Dialog {
    private final EventDispatcher dispatcher = new EventDispatcher();
    private Label error = null;

    public FormDialog() {
      addClassName("loginForm");
      setMaxWidth("450px");
      setMoveable(false);
      setCloseable(false);
      setAutoFocus(true);

      // header
      // =======
      Label title = new Label("Adminstrator Login");
      getHeader().add(title);

      // content
      // =======
      Label help = new Label("Please enter your email address and password to enter the customer portal.");

      error = new Label();
      error.setVisible(false);
      error.addClassName("loginForm__error");

      TextBox username = new TextBox();
      username.setAttribute("label", "Username");
      username.setAttribute("placeholder", "Enter your name");

      TextBox password = new TextBox();
      password.setAttribute("type", "password");
      password.setAttribute("label", "Password");
      password.setAttribute("placeholder", "Enter your password");

      getContent().add(help, error, username, password);

      // Footer
      // =======
      CheckBox rememberMe = new CheckBox();
      rememberMe.setChecked(true);
      rememberMe.setText("Remember me");

      Button login = new Button("Login");
      login.setTheme(Button.Theme.PRIMARY);
      login.onClick((e) -> {
        Map<String, Object> data = new HashMap<>();
        data.put("username", username.getText());
        data.put("password", password.getText());
        data.put("rememberMe", rememberMe.isChecked());
        dispatcher.dispatchEvent(new LoginEvent(this, data));
      });

      getFooter().add(rememberMe, login);
    }

    /**
     * Show an error message.
     * 
     * @param message the message
     */
    public void showError(String message) {
      this.error.setText(message);
      this.error.setVisible(true);
    }

    /**
     * Add a login listener.
     * 
     * @param listener the listener
     * @return this
     */
    public Dialog addLoginListener(EventListener<LoginEvent> listener) {
      dispatcher.addEventListener(LoginEvent.class, listener);
      return this;
    }

    /**
     * Remove a login listener.
     * 
     * @param listener the listener
     * @return this
     */
    public Dialog removeLoginListener(EventListener<LoginEvent> listener) {
      dispatcher.removeEventListener(LoginEvent.class, listener);
      return this;
    }
  }

  /**
   * Emmited when the user click on the login button.
   */
  private final class LoginEvent extends Event<Dialog> {
    /**
     * Creates a new event.
     * 
     * @param control  the control
     * @param eventMap the event map
     */
    public LoginEvent(Dialog control, Map<String, Object> eventMap) {
      super(control, eventMap);
    }

    /**
     * Get the username entered by the user.
     * 
     * @return the username
     */
    public String getUserName() {
      return (String) getData().get("username");
    }

    /**
     * Get the password entered by the user.
     * 
     * @return the password
     */
    public String getPassword() {
      return (String) getData().get("password");
    }

    /**
     * Check if the user checked the remember me checkbox.
     * 
     * @return true if the user checked the remember me checkbox
     */
    public boolean isRememberMe() {
      return (boolean) getData().get("rememberMe");
    }
  }
}
```

**Comment by StephanWald** [comment]
nice. go ahead and merge when you deem apropriate

**Comment by hyyan** [comment]
@mhawkinsbasis The following is for documentation purposes. Let me know if you have any questions about the implementation.

## Integrate A Custom Built Component  (Client-server component)

counter

```js
/**
 * A simple animated counter card component.
 * 
 * @element dwcj-animated-counter
 * @slot icon - The icon slot.
 * 
 * @attr {String} lang - The language code for the number format.
 * @attr {String} format-options - The options for the number format.
 * @attr {String} label - The label of the card.
 * @attr {Number} start - The start value of the counter.
 * @attr {Number} speed - The speed of the animation.
 * @attr {String} theme - The theme of the card. Supported values are: `primary`, `danger`, `success`, `info`, `warning`.
 * @attr {Number} value - The value of the counter.
 * 
 * @author Hyyan Abo Fakher
 */
class DwcjAnimatedCard extends HTMLElement {
  #propFormatLang;
  #propFormatOptions;
  #propLabel;
  #propStart;
  #propSpeed;
  #propTheme;
  #propValue;
  #view = /* html */`
        <style>
          :host {
            display: inline-block;
          }
  
          [part="card"] {
            display: flex;
            align-items: center;
            padding: 1.5rem;
            border-radius: var(--bbj-border-radius);
            background-color: var(--bbj-surface-3);
            border: 1px solid var(--bbj-color-default);
            gap: 1.5rem;
            width: 100%;
          }
  
          [part="content"] {
            flex: 1;
            display: flex;
            flex-direction: column;
          }
  
          [part="value"] {
            font-size: 2.5rem;
            font-weight: var(--bbj-font-weight-bolder);
          }
  
          [part="label"] {
            font-size: 1.1rem;
            color: var(--bbj-color-gray-text-light);
          }
  
          :host ::slotted([slot="icon"]) {
            display: flex;
            font-size: 2.5rem;
            color: var(--bbj-color-gray-text-light);
            border-radius: var(--bbj-border-radius-round);
            border: thin solid black;
            padding: 1rem;
          }
  
          :host([theme="primary"]) ::slotted([slot="icon"]) {
            color: var(--bbj-color-primary);
            border-color: var(--bbj-color-primary);
            background-color: var(--bbj-color-primary-alt);
          }
  
          :host([theme="danger"]) ::slotted([slot="icon"]) {
            color: var(--bbj-color-danger);
            border-color: var(--bbj-color-danger);
            background-color: var(--bbj-color-danger-alt);
          }
  
          :host([theme="success"]) ::slotted([slot="icon"]) {
            color: var(--bbj-color-success);
            border-color: var(--bbj-color-success);
            background-color: var(--bbj-color-success-alt);
          }
  
          :host([theme="info"]) ::slotted([slot="icon"]) {
            color: var(--bbj-color-info);
            border-color: var(--bbj-color-info);
            background-color: var(--bbj-color-info-alt);
          }
  
          :host([theme="warning"]) ::slotted([slot="icon"]) {
            color: var(--bbj-color-warning);
            border-color: var(--bbj-color-warning);
            background-color: var(--bbj-color-warning-alt);
          }
        </style>
        <div part="card">
          <slot name="icon"></slot>
          <div part="content">
            <div part="value"></div>
            <div part="label"></div>
          </div>
        </div>
      `;

  /**
   * Create a new AnimatedCounterCard
   */
  constructor() {
    super();
    this.attachShadow({ mode: 'open' });
    this.shadowRoot.innerHTML = this.#view;
    this.formatOptions = {
      style: 'currency',
      currency: 'USD',
      minimumFractionDigits: 2,
      maximumFractionDigits: 2
    };
    this.lang = "en-US";
    this.label = "";
    this.start = 0;
    this.speed = 1000;
    this.theme = "";
    this.value = 0;
  }

  /**
   * Observe the attributes for changes.
   * 
   * @returns {Array} The list of attributes to observe.
   */
  static get observedAttributes() {
    return [
      'format-options',
      'lang',
      'label',
      'start',
      'speed',
      'theme',
      'value'
    ];
  }

  connectedCallback() {
    this.#animateValue(this.value);
  }

  /** 
   * Sync the attribute changes with the properties.
   * 
   * @param {String} name The name of the attribute.
   * @param {String} oldValue The old value of the attribute.
   * @param {String} newValue The new value of the attribute.
   */
  attributeChangedCallback(name, oldValue, newValue) {
    if (oldValue === newValue) return;
    switch (name) {
      case 'lang':
        this.lang = newValue;
        break;
      case 'format-options':
        this.formatOptions = JSON.parse(newValue);
        break;
      case 'label':
        this.label = newValue;
        break;
      case 'start':
        this.start = parseInt(newValue);
        break;
      case 'speed':
        this.speed = parseInt(newValue);
        break;
      case 'value':
        this.value = parseInt(newValue);
        break;
      case 'theme':
        this.theme = newValue;
        break;
    }
  }

  /**
   * Get the start value.
   * 
   * @returns {Number} The start value.
   */
  get start() {
    return this.#propStart;
  }

  /**
   * Set the start value.
   * 
   * The start value is the value the counter will start animating from.
   * 
   * @param {Number} value The start value.
   */
  set start(value) {
    this.#propStart = value;
  }

  /**
   * Get the value
   * 
   * @returns {Number} The value.
   */
  get value() {
    return this.#propValue;
  }

  /**
   * Set the value
   * 
   * @param {Number} value The value to set.
   */
  set value(value) {
    this.#propValue = value;
    this.#animateValue(value);
  }

  /**
   * Get the animation speed.
   * 
   * @returns {Number} The animation speed.
   */
  get speed() {
    return this.#propSpeed;
  }

  /**
   * Set the animation speed.
   * 
   * @param {Number} value The speed to set.
   */
  set speed(value) {
    this.#propSpeed = value;
  }

  /**
   * Get the label.
   * 
   * @returns {String} The label.
   */
  get label() {
    return this.#propLabel;
  }

  /**
   * Set the label.
   * 
   * @param {String} value The label to set.
   */
  set label(value) {
    this.#propLabel = value;
    this.shadowRoot.querySelector('[part="label"]').innerHTML = value;
  }

  /**
   * Get the language.
   * 
   * @returns {String} The language.
   */
  get lang() {
    return this.#propFormatLang;
  }

  /**
   * Set the language.
   * 
   * @param {String} value The language to set.
   */
  set lang(value) {
    this.#propFormatLang = value;
    this.value = this.value;
  }

  /**
   * Get the format options.
   * 
   * @returns {Object} The format options.
   * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString
   */
  get formatOptions() {
    return this.#propFormatOptions;
  }

  /**
   * Set the format options.
   * 
   * @param {Object} value The format options to set.
   * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString
   */
  set formatOptions(value) {
    this.#propFormatOptions = value;
    this.value = this.value;
  }

  /**
   * Get the theme.
   * 
   * @returns {String} The theme.
   */
  get theme() {
    return this.#propTheme;
  }

  /**
   * Set the theme.
   * 
   * Supported themes are: `primary`, `danger`, `success`, `info`, `warning`.
   * 
   * @param {String} value The theme to set.
   */
  set theme(value) {
    this.#propTheme = value;
    // reflect to attribute
    this.setAttribute('theme', value);
  }

  /**
   * Format the given value using the current format options.
   * 
   * @param {*} value 
   * @returns {String} The formatted value.
   * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString
   */
  #formatValue(value) {
    if (typeof value === 'string') {
      value = parseFloat(value);
    }

    if (isNaN(value)) {
      return value;
    }

    return value.toLocaleString(this.lang, this.formatOptions);
  }

  /**
   * Animate the card's value.
   * 
   * @param {Number} value The value to animate to.
   */
  #animateValue(value) {
    const start = this.start;
    const duration = this.speed;

    let startTimestamp = null;
    const step = (timestamp) => {
      if (!startTimestamp) startTimestamp = timestamp;
      const progress = Math.min((timestamp - startTimestamp) / duration, 1);
      this.shadowRoot.querySelector('[part="value"]').innerHTML = this.#formatValue(
        Math.floor(progress * (value - start) + start)
      );
      if (progress < 1) {
        window.requestAnimationFrame(step);
      }
    };

    window.requestAnimationFrame(step);
  }
}

// define the custom element
customElements.define('dwcj-animated-counter', DwcjAnimatedCard);
```

```java

import org.dwcj.annotations.InlineJavaScript;
import org.dwcj.interfaces.HasClassName;
import org.dwcj.interfaces.HasStyle;
import org.dwcj.webcomponent.PropertyDescriptor;
import org.dwcj.webcomponent.WebComponent;
import org.dwcj.webcomponent.annotations.NodeName;

/**
 * An interface for animated counter web component
 * 
 * @author Hyyan Abo Fakher
 */
@InlineJavaScript(id = "dwcj-animated-counter", local = true, once = true, value = "components/dwcj-animated-counter.js")
@NodeName("dwcj-animated-counter")
public final class AnimatedCounter extends WebComponent implements HasClassName, HasStyle {

  /**
   * The theme of the card
   */
  public enum Theme {
    PRIMARY("primary"),
    DANGER("danger"),
    SUCCESS("success"),
    INFO("info"),
    WARNING("warning"),
    DEFAULT("");

    private final String value;

    private Theme(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    public static Theme fromValue(String value) {
      for (Theme theme : Theme.values()) {
        if (theme.value.equals(value)) {
          return theme;
        }
      }
      return null;
    }
  }

  private final PropertyDescriptor<String> LABEL = PropertyDescriptor.property("label", "");
  private final PropertyDescriptor<Integer> START = PropertyDescriptor.property("start", 0);
  private final PropertyDescriptor<Integer> SPEED = PropertyDescriptor.property("speed", 1000);
  private final PropertyDescriptor<String> THEME = PropertyDescriptor.property("theme", Theme.DEFAULT.getValue());
  private final PropertyDescriptor<Double> VALUE = PropertyDescriptor.property("value", 0.0);

  /**
   * Create a new AnimatedCounter instance
   */
  public AnimatedCounter() {
    super();
  }

  /**
   * Create a new AnimatedCounter instance
   * 
   * @param label the label
   * @param value the value
   * @param theme the theme
   */
  public AnimatedCounter(String label, double value, Theme theme) {
    super();
    setLabel(label);
    setValue(value);
    setTheme(theme);
  }

  /**
   * Create a new AnimatedCounter instance
   * 
   * @param label the label
   * @param value the value
   */
  public AnimatedCounter(String label, double value) {
    this(label, value, Theme.DEFAULT);
  }

  /**
   * Set the icon of the card
   * 
   * @param name the name of the icon
   * @param pool the pool of the icon
   * 
   * @return this
   */
  public AnimatedCounter setIcon(String name, String pool) {
    addRawSlot("icon", "<bbj-icon name=\"" + name + "\" pool=\"" + pool + "\"></bbj-icon>");
    return this;
  }

  /**
   * Set the icon of the card
   * 
   * @param name the name of the icon
   * 
   * @return this
   */
  public AnimatedCounter setIcon(String name) {
    return setIcon(name, "tabler");
  }

  /**
   * Set the card's label
   * 
   * @param label the label
   * @return this
   */
  public AnimatedCounter setLabel(String label) {
    set(LABEL, label);
    return this;
  }

  /**
   * Get the card's label
   * 
   * @return the label
   */
  public String getLabel() {
    return get(LABEL);
  }

  /**
   * Set the start value of the counter
   * 
   * The start value is the value the counter will start animating from.
   * 
   * @param start the start value
   * @return this
   */
  public AnimatedCounter setStart(int start) {
    set(START, start);
    return this;
  }

  /**
   * Get the start value of the counter
   * 
   * @return the start value
   */
  public int getStart() {
    return get(START);
  }

  /**
   * Set the speed of the animation
   * 
   * @param speed the speed
   * @return this
   */
  public AnimatedCounter setSpeed(int speed) {
    set(SPEED, speed);
    return this;
  }

  /**
   * Get the speed of the animation
   * 
   * @return the speed
   */
  public int getSpeed() {
    return get(SPEED);
  }

  /**
   * Set the theme of the card
   * 
   * @param theme the theme
   * @return this
   */
  public AnimatedCounter setTheme(Theme theme) {
    set(THEME, theme.getValue());
    return this;
  }

  /**
   * Get the theme of the card
   * 
   * @return the theme
   */
  public Theme getTheme() {
    return Theme.fromValue(get(THEME));
  }

  /**
   * Set the value of the counter
   * 
   * @param value the value
   * @return this
   */
  public AnimatedCounter setValue(double value) {
    set(VALUE, value);
    return this;
  }

  /**
   * Get the value of the counter
   * 
   * @return the value
   */
  public double getValue() {
    return get(VALUE);
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public AnimatedCounter addClassName(String className) {
    addComponentClassName(className);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public AnimatedCounter removeClassName(String className) {
    removeComponentClassName(className);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public AnimatedCounter setStyle(String property, String value) {
    setComponentStyle(property, value);
    return this;
  }

}
```

```java
import org.dwcj.App;
import org.dwcj.annotations.InlineStyleSheet;
import org.dwcj.controls.panels.AppPanel;
import org.dwcj.controls.panels.Div;
import org.dwcj.exceptions.DwcException;

@InlineStyleSheet(value = "" +
    ".cardContainer {" +
    "   display: flex;" +
    "   flex-direction: column;" +
    "   align-items: center;" +
    "   gap: 1rem;" +
    "   padding: 2rem;" +
    "}")
public class Cards extends App {

  /**
   * {@inheritDoc}
   */
  @Override
  public void run() throws DwcException {
    AppPanel panel = new AppPanel();

    Div container = new Div();
    container.addClassName("cardContainer");

    // loop over card supported themes and create a card for each theme
    for (AnimatedCounter.Theme theme : AnimatedCounter.Theme.values()) {
      AnimatedCounter card = new AnimatedCounter("Total Revenue", 58.947);
      card.setIcon("shopping-cart");
      card.setTheme(theme);
      card.setStyle("width", "275px");
      container.add(card);
    }

    panel.add(container);
  }
}
```

**Comment by hyyan** [comment]
@mhawkinsbasis The following is for documentation purposes. Let me know if you have any questions about the implementation.

## Integrate A third party Component  (Client-server component)

Recording 2023-01-04 at 03 01 49

```java
package org.demo;

import java.awt.Color;

import org.dwcj.annotations.Attribute;
import org.dwcj.annotations.JavaScript;
import org.dwcj.webcomponent.PropertyDescriptor;
import org.dwcj.webcomponent.WebComponent;
import org.dwcj.webcomponent.annotations.NodeName;

/**
 * QRCode Generator using Shoelace QRCode component
 * 
 * @author Hyyan Abo Fakher
 */
@JavaScript(url = "https://cdn.jsdelivr.net/npm/@shoelace-style/shoelace@2.0.0-beta.87/dist/shoelace.js", attributes = {
    @Attribute(name = "type", value = "module")
})
@NodeName("sl-qr-code")
public final class QRCode extends WebComponent {

  private final PropertyDescriptor<String> VALUE = PropertyDescriptor.property("value", "");
  private final PropertyDescriptor<Integer> SIZE = PropertyDescriptor.property("size", 200);
  private final PropertyDescriptor<String> COLOR = PropertyDescriptor.property("fill", "#000000");

  /**
   * Create a new QRCode
   */
  public QRCode() {
    super();
  }

  /**
   * Create a new QRCode with the given value
   * 
   * @param value the value of the QRCode
   */
  public QRCode(String value) {
    super();
    this.setValue(value);
  }

  /**
   * Create a new QRCode with the given value and size
   * 
   * @param value the value of the QRCode
   * @param size  the size of the QRCode
   */
  public QRCode(String value, int size) {
    super();
    this.setValue(value);
    this.setSize(size);
  }

  /**
   * Get the value of the QRCode
   * 
   * @return the value of the QRCode
   */
  public String getValue() {
    return get(VALUE);
  }

  /**
   * Set the value of the QRCode
   * 
   * @param value the value of the QRCode
   */
  public QRCode setValue(String value) {
    set(VALUE, value);
    return this;
  }

  /**
   * Get the size of the QRCode
   * 
   * @return the size of the QRCode
   */
  public int getSize() {
    return get(SIZE);
  }

  /**
   * Set the size of the QRCode
   * 
   * @param size the size of the QRCode
   */
  public QRCode setSize(int size) {
    set(SIZE, size);
    return this;
  }

  /**
   * Get the color of the QRCode
   * 
   * @return the color of the QRCode
   */
  public Color getColor() {
    String hex = get(COLOR);
    return Color.decode(hex);
  }

  /**
   * Set the color of the QRCode
   * 
   * @param color the color of the QRCode
   */
  public QRCode setColor(Color color) {
    String hex = String.format("#%02x%02x%02x", color.getRed(), color.getGreen(), color.getBlue());
    set(COLOR, hex);
    return this;
  }
}
```

```java
package org.demo;

import java.awt.Color;
import org.dwcj.App;
import org.dwcj.annotations.AppTheme;
import org.dwcj.annotations.AppTitle;
import org.dwcj.annotations.InlineStyleSheet;
import org.dwcj.controls.panels.AppPanel;
import org.dwcj.controls.textbox.TextBox;
import org.dwcj.exceptions.DwcException;

@AppTheme("dark")
@AppTitle("QR Code Generator")
@InlineStyleSheet(value = "" +
    ".app-panel{" +
    "  overflow-y: auto;" +
    "  display: flex;" +
    "  align-items: center;" +
    "  justify-content: center;" +
    "  flex-direction: column;" +
    "  gap: 1rem;" +
    "  height: 100%;" +
    "}")
public class QRSample extends App {

  private static final String DEFAULT_VALUE = "https://dwcj.org/";

  @Override
  public void run() throws DwcException {
    AppPanel panel = new AppPanel();
    panel.addClassName("app-panel");

    QRCode qr = new QRCode(DEFAULT_VALUE);
    qr.setSize(200);
    qr.setSize(qr.getSize());
    qr.setColor(Color.ORANGE);

    TextBox editBox = new TextBox();
    editBox.setText(DEFAULT_VALUE);
    editBox.setExpanse(TextBox.Expanse.LARGE);
    editBox.setAttribute("placeholder", "Enter a value");
    editBox.onEditModify((e) -> {
      qr.setValue(editBox.getText());
    });

    panel.add(qr, editBox);
  }
}
```

**Comment by hyyan** [comment]
@mhawkinsbasis  See https://github.com/DwcJava/engine/pull/233

**Pull request merged**
