### PR TITLE
fix: DOM manipulation before the custom element definition on the browser

### PR DESCRIPTION
**Pull request by ElyasSalar**
### Purpose
This PR aims to put any DOM manipulation in pending over web components in the browser which is not yet defined. This will overcome the issue where we made DOM manipulations over web components even before they were defined in the browser's custom elements registry.

For more context, you can look at this [replit](https://replit.com/@ElyasDev/bbj-component-demo#index.html).

### CODE REVIEW

**Comment by hyyan** [comment]
@ElyasSalar I'm not sure what exactly you're trying to fix. Can you share a piece of code that illustrates the problem?

Right now, this PR is a bit of a hack that will make things slower when working with integrated web components.

**Comment by StephanWald** [comment]
@hyyan pls compare to my recent "hack" with the [setWhenLoaded](https://github.com/DwcJava/engine/blob/9d9837cc0f66daca35b891c58090cf7083b3ace4/dwcj-engine/src/main/resources/webcomponent/wcconnector.js#L34) function which is probably worse than using the whenDefined promise. Jim does the same in his new implementation of BBjWebComponent. 

We need something to make sure that properties don't get ignored because the component is not ready and the whenDefined promise seems viable. If there is a better way then we'll have to go it, but there are webcomponents out there that do not signal their readiness with a hydrated attribute or classname so we probably need something like this as a safeguard.

https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/whenDefined

**Comment by hyyan** [comment]
@StephanWald Which component is this? Where is the code located? Whatever the purpose of this 'setLoaded' function might be, it is not suitable for inclusion here. Every web component must be able to accommodate property changes once the component has been fully loaded. If a component fails to fulfill this requirement, it indicates a problem within the library or the component itself that should be brought to attention. As mentioned, this pull request represents a workaround that is not appropriate in this context.

**Comment by hyyan** [comment]
https://shoelace.style/getting-started/usage#component-rendering-and-updating


https://stenciljs.com/docs/api#componentonready

**Comment by hyyan** [comment]
invoke, addEventListener, and removeEventListener should not be dependent on the component being defined. These methods function with HtmlElement APIs, which are accessible for any custom node, whether or not it has been associated with a web component implementation.

**Comment by StephanWald** [comment]
@hyyan We faced this type of problem with SAP's UI5 components but also with Elyas' menu component.  Please point me to where the existing implementation of the Java WebComponent class checks for the readiness of the web component in the client and makes sure not to try setting properties before it's loaded. I didn't find that place, but if it exists this workaround might indeed be unnecessary or in the wrong spot.

**Comment by StephanWald** [comment]
invoke does not work as long as the component is undefined.

**Comment by hyyan** [comment]
The WebComponent Class must not be responsible for verifying the component's readiness. Each web component library has its unique criteria for determining readiness. Please refer to the links I shared earlier. Elyas is utilizing StencilJS, which effectively manages updates once the component is fully loaded. It ensures that no properties you define are overlooked. The only scenario where waiting for component readiness might be necessary is when invoking a method on a lazily loaded component. In such cases, you can utilize the WebComponent API to execute an expression within the component's context and make the method call.

**Comment by ElyasSalar** [comment]
@hyyan Sorry for not addressing a reproducible issue initially, I assumed that we're all aware of it.

I have written a small [replit](https://replit.com/@ElyasDev/bbj-component-demo#index.html) to simulate the issue this PR aims to resolve and update the description.

We recently tried to load JavaScript components extraordinarily to how we were doing it for core [basis-next](https://github.com/BasisHub/basis-next) components. For basis-next components we initially add a script reference to a file named `bbj-ui.esm.js` generated at build time, That file has all the names of components and their attributes and properties and it will define them directly in the custom elements registry. This is a [replit](https://replit.com/@ElyasDev/RunnyDearestKeyboard#script.js) I wrote for myself as proof of my understanding, after `bbj-ui.esm.js` defined all the components, then Stencil internally will run this [connectedCallback](https://github.com/ionic-team/stencil/blob/b0efde49396e2876392c56ab07412979712e7994/src/runtime/connected-callback.ts#L13) on any new element that's being added to the DOM to [initialize the component](https://github.com/ionic-team/stencil/blob/b0efde49396e2876392c56ab07412979712e7994/src/runtime/connected-callback.ts#L99) and then [load that component](https://github.com/ionic-team/stencil/blob/b0efde49396e2876392c56ab07412979712e7994/src/runtime/initialize-component.ts#L29). After loading the component Stencil remembers the previously set attributes and properties and won't let them overridden by the defaults of the newly loaded component.

Having that context, if we wanted to load the JavaScript components in parallel to Java class DOM manipulation or after that like we have [here](https://github.com/DwcJava/kitchen/blob/main/src/main/java/org/dwcj/kitchen/multiselectcombo/MultiSelectComboBox.java#L16C1-L21C93), the JavaScript components will load after the DOM manipulations which cause the previously set attributes and properties to be overridden simply because loading the JavaScript file is asynchronous and takes longer than DOM manipulations.

In order to overcome that issue, I wanted to find a spot where the Java class components trigger changes to be kept pending until the component that the Java class wants to make changes over is defined. I saw that @StephanWald made changes to this `wcconnector.js` file, I thought this would be a good spot to apply that change.

>Right now, this PR is a bit of a hack that will make things slower when working with integrated web components.

Regarding your comment, I'm not sure what exactly but if you mean that this will affect the performance when the Java class components try to communicate through this connector, then I don't think so because `whenDefined` is just a promise that will let the execution happen as soon as the component is defined, otherwise it will be kept in pending. This won't affect the core components of the basis-next since all the components are defined initially.

Now that we know the problem, I was/am love to have your thoughts on this.

**Comment by hyyan** [comment]
A substantial refactoring is currently being planned, and [wcconnector.js](https://github.com/DwcJava/engine/pull/405/files#diff-84c82f55929b667911a8910ea236f41ce0c530e1ea5971e90b9274781bdf7180) is being removed.

**Pull request closed without merging**
